<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'5paw6Ze75Yqo5oCB');
$cfg_Cs[3]=array(0,2,1,'5Lqn5ZOB5Lit5b+D');
$cfg_Cs[20]=array(2,1,1,'6KGM5Lia5Yqo5oCB');
$cfg_Cs[10]=array(0,2,1,'57uP5YW45bel56iL');
$cfg_Cs[19]=array(2,1,1,'5YWs5Y+45paw6Ze7');
$cfg_Cs[14]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[15]=array(1,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[16]=array(1,1,1,'5LyB5Lia5Y6G56iL');
$cfg_Cs[17]=array(1,1,1,'5LyB5Lia5paH5YyW');
$cfg_Cs[18]=array(1,1,1,'6ZuG5Zui6I2j6KqJ');
?>