<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/170329/1-1F329161603.jpg ",93,253);
$z[1][4]['ddimg']="/uploads/allimg/170329/1-1F329161603.jpg";
$z[1][4]['text']="吉尼斯米黄";
$z[1][4]['width']="961";
$z[1][4]['height']="660";
$z[2]=Array("img"," /uploads/allimg/170329/1-1F329161635.jpg ",255,415);
$z[2][4]['ddimg']="/uploads/allimg/170329/1-1F329161635.jpg";
$z[2][4]['text']="吉尼斯米黄";
$z[2][4]['width']="960";
$z[2][4]['height']="696";
$z[3]=Array("img"," /uploads/allimg/170329/1-1F329161637.jpg ",417,577);
$z[3][4]['ddimg']="/uploads/allimg/170329/1-1F329161637.jpg";
$z[3][4]['text']="吉尼斯米黄";
$z[3][4]['width']="898";
$z[3][4]['height']="660";

?>