{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/170329/1-1F329161603.jpg' text='吉尼斯米黄' width='961' height='660'} /uploads/allimg/170329/1-1F329161603.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/170329/1-1F329161635.jpg' text='吉尼斯米黄' width='960' height='696'} /uploads/allimg/170329/1-1F329161635.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/170329/1-1F329161637.jpg' text='吉尼斯米黄' width='898' height='660'} /uploads/allimg/170329/1-1F329161637.jpg {/dede:img}
