{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/170329/1-1F3291H036.jpg' text='成都锦尚酒店' width='960' height='677'} /uploads/allimg/170329/1-1F3291H036.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/170329/1-1F3291H038.jpg' text='成都锦尚酒店' width='1280' height='960'} /uploads/allimg/170329/1-1F3291H038.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/170329/1-1F3291H041.jpg' text='成都锦尚酒店' width='1280' height='960'} /uploads/allimg/170329/1-1F3291H041.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/170329/1-1F3291H043.jpg' text='成都锦尚酒店' width='1280' height='960'} /uploads/allimg/170329/1-1F3291H043.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/170329/1-1F3291H107.jpg' text='成都锦尚酒店' width='1280' height='960'} /uploads/allimg/170329/1-1F3291H107.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/170329/1-1F3291H110.jpg' text='成都锦尚酒店' width='1280' height='960'} /uploads/allimg/170329/1-1F3291H110.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/170329/1-1F3291H115.jpg' text='成都锦尚酒店' width='1280' height='960'} /uploads/allimg/170329/1-1F3291H115.jpg {/dede:img}
