<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/170329/1-1F329222048.jpg ",93,253);
$z[1][4]['ddimg']="/uploads/allimg/170329/1-1F329222048.jpg";
$z[1][4]['text']="金色维也纳";
$z[1][4]['width']="960";
$z[1][4]['height']="660";

?>