<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/170329/1-1F329222449.jpg ",93,250);
$z[1][4]['ddimg']="/uploads/allimg/170329/1-1F329222449.jpg";
$z[1][4]['text']="曼陀罗灰";
$z[1][4]['width']="960";
$z[1][4]['height']="638";
$z[2]=Array("img"," /uploads/allimg/170329/1-1F329222450.jpg ",252,409);
$z[2][4]['ddimg']="/uploads/allimg/170329/1-1F329222450.jpg";
$z[2][4]['text']="曼陀罗灰";
$z[2][4]['width']="960";
$z[2][4]['height']="681";

?>