<?php
$z[0]=Array("field","",301,320);
$z[0][4]['name']="title";
$z[1]=Array("global","",321,347);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1256,1295);
$z[2][4]['filename']="header_m.htm";
$z[3]=Array("field","",1525,1554);
$z[3][4]['name']="typename";
$z[4]=Array("global","",1897,1922);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("channel","\r\n        <li> <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\">&#xe60c;</span>\r\n          <dl>\r\n          </dl>\r\n        </li>\r\n        ",2333,2721);
$z[5][4]['type']="son";
$z[5][4]['row']="10";
$z[5][4]['typeid']="3";
$z[5][4]['currentstyle']="<li class='hover'><a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";
$z[6]=Array("field","",2818,2837);
$z[6][4]['name']="title";
$z[7]=Array("field","",2886,2904);
$z[7][4]['name']="body";
$z[8]=Array("prenext","",2924,2952);
$z[8][4]['get']="prewap";
$z[9]=Array("prenext","",2954,2983);
$z[9][4]['get']="nextwap";
$z[10]=Array("type"," <a href=\"list.php?tid=[field:id/]\" title=\"返回列表\" class=\"back\">返回列表</a> ",2984,3094);
$z[11]=Array("include","",3115,3154);
$z[11][4]['filename']="footer_m.htm";

?>