<li>
        <div> <a href="[field:arcurl/]" title="[field:title/]"><img src="[field:picname/]" alt="[field:title/]"/></a>
          <p class="pg-border-color pro5-border1"></p>
          <p class="pg-border-color pro5-border2"></p>
          <p class="pg-border-color pro5-border3"></p>
          <p class="pg-border-color pro5-border4"></p>
        </div>
        <p><a href="[field:arcurl/]" title="[field:title/]" class="pg-color">[field:title/]</a></p>
      </li>