{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/170329/1-1F329222I0.jpg' text='宇化石' width='960' height='664'} /uploads/allimg/170329/1-1F329222I0.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/170329/1-1F329222I2.jpg' text='宇化石' width='640' height='472'} /uploads/allimg/170329/1-1F329222I2.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/170329/1-1F329222I3.jpg' text='宇化石' width='960' height='664'} /uploads/allimg/170329/1-1F329222I3.jpg {/dede:img}
