<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/170329/1-1F329222I0.jpg ",93,245);
$z[1][4]['ddimg']="/uploads/allimg/170329/1-1F329222I0.jpg";
$z[1][4]['text']="宇化石";
$z[1][4]['width']="960";
$z[1][4]['height']="664";
$z[2]=Array("img"," /uploads/allimg/170329/1-1F329222I2.jpg ",247,399);
$z[2][4]['ddimg']="/uploads/allimg/170329/1-1F329222I2.jpg";
$z[2][4]['text']="宇化石";
$z[2][4]['width']="640";
$z[2][4]['height']="472";
$z[3]=Array("img"," /uploads/allimg/170329/1-1F329222I3.jpg ",401,553);
$z[3][4]['ddimg']="/uploads/allimg/170329/1-1F329222I3.jpg";
$z[3][4]['text']="宇化石";
$z[3][4]['width']="960";
$z[3][4]['height']="664";

?>