<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/170329/1-1F329222258.jpg ",93,251);
$z[1][4]['ddimg']="/uploads/allimg/170329/1-1F329222258.jpg";
$z[1][4]['text']="维罗纳灰";
$z[1][4]['width']="1280";
$z[1][4]['height']="960";
$z[2]=Array("img"," /uploads/allimg/170329/1-1F329222300.jpg ",253,410);
$z[2][4]['ddimg']="/uploads/allimg/170329/1-1F329222300.jpg";
$z[2][4]['text']="维罗纳灰";
$z[2][4]['width']="800";
$z[2][4]['height']="600";
$z[3]=Array("img"," /uploads/allimg/170329/1-1F329222301.jpg ",412,570);
$z[3][4]['ddimg']="/uploads/allimg/170329/1-1F329222301.jpg";
$z[3][4]['text']="维罗纳灰";
$z[3][4]['width']="1280";
$z[3][4]['height']="960";
$z[4]=Array("img"," /uploads/allimg/170329/1-1F329222302.jpg ",572,729);
$z[4][4]['ddimg']="/uploads/allimg/170329/1-1F329222302.jpg";
$z[4][4]['text']="维罗纳灰";
$z[4][4]['width']="960";
$z[4][4]['height']="698";
$z[5]=Array("img"," /uploads/allimg/170329/1-1F329222303.jpg ",731,889);
$z[5][4]['ddimg']="/uploads/allimg/170329/1-1F329222303.jpg";
$z[5][4]['text']="维罗纳灰";
$z[5][4]['width']="1280";
$z[5][4]['height']="960";

?>