<?php
$z[0]=Array("channel","\r\n      <li> <a href=\"[field:typeurl/]\">[field:typename/]</a> </li>\r\n      ",108,223);
$z[0][4]['type']="top";
$z[1]=Array("flink","  [field:link /]  ",372,450);
$z[1][4]['titlelen']="20";
$z[1][4]['row']="20";
$z[1][4]['type']="text";
$z[2]=Array("global","",505,526);
$z[2][4]['name']="cfg_dz";
$z[3]=Array("global","",558,579);
$z[3][4]['name']="cfg_sj";
$z[4]=Array("global","",594,615);
$z[4][4]['name']="cfg_dh";
$z[5]=Array("global","",733,757);
$z[5][4]['name']="cfg_beian";
$z[6]=Array("global","",775,801);
$z[6][4]['name']="cfg_powerby";
$z[7]=Array("global","",955,976);
$z[7][4]['name']="cfg_dh";
$z[8]=Array("global","",1253,1274);
$z[8][4]['name']="cfg_qq";

?>