<?php
$z[0]=Array("channel","\r\n      <li> <a href=\"[field:typeurl/]\">[field:typename/]</a> </li>\r\n      ",108,223);
$z[0][4]['type']="top";
$z[1]=Array("flink","  [field:link /]  ",372,450);
$z[1][4]['titlelen']="20";
$z[1][4]['row']="20";
$z[1][4]['type']="text";
$z[2]=Array("global","",505,526);
$z[2][4]['name']="cfg_dz";
$z[3]=Array("global","",558,579);
$z[3][4]['name']="cfg_sj";
$z[4]=Array("global","",655,679);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",697,723);
$z[5][4]['name']="cfg_powerby";
$z[6]=Array("global","",1174,1195);
$z[6][4]['name']="cfg_qq";
$z[7]=Array("global","",1338,1370);
$z[7][4]['name']="cfg_templets_skin";

?>