<?php
$z[0]=Array("channel","\r\n      <li> <a href=\"[field:typeurl/]\">[field:typename/]</a> </li>\r\n      ",111,226);
$z[0][4]['type']="top";
$z[1]=Array("flink","  [field:link /]  ",373,451);
$z[1][4]['titlelen']="20";
$z[1][4]['row']="20";
$z[1][4]['type']="text";
$z[2]=Array("global","",497,518);
$z[2][4]['name']="cfg_dz";
$z[3]=Array("global","",534,555);
$z[3][4]['name']="cfg_dh";
$z[4]=Array("global","",570,591);
$z[4][4]['name']="cfg_dh";
$z[5]=Array("global","",698,722);
$z[5][4]['name']="cfg_beian";
$z[6]=Array("global","",740,766);
$z[6][4]['name']="cfg_powerby";
$z[7]=Array("global","",1032,1053);
$z[7][4]['name']="cfg_qq";

?>