<?php
$z[0]=Array("global","",392,418);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","(@me==\"\")? @me=\" class='on' \":@me=\"\";",959,1046);
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n        ",1086,1320);
$z[2][4]['type']="top";
$z[2][4]['currentstyle']="<li class='on'><a href='~typelink~' title='~typename~'>~typename~</a> </li>";

?>