<?php
$z[0]=Array("global","",364,396);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",419,445);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","(@me==\"\")? @me=\" class='on' \":@me=\"\";",986,1073);
$z[2][4]['name']="typeid";
$z[2][4]['runphp']="yes";
$z[3]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n        ",1113,1347);
$z[3][4]['type']="top";
$z[3][4]['currentstyle']="<li class='on'><a href='~typelink~' title='~typename~'>~typename~</a> </li>";

?>