<?php
$z[0]=Array("global","",392,418);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","(@me==\"\")? @me=\" class='on' \":@me=\"\";",959,1046);
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("channelartlist","\r\n        <li class=\"{dede:field.currentstyle/}\"> <a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a>\r\n        </li>\r\n        ",1086,1345);
$z[2][4]['typeid']="top";
$z[2][4]['currentstyle']="on";

?>