<?php
$z[0]=Array("global","",349,375);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","(@me==\"\")? @me=\" class='on' \":@me=\"\";",734,821);
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("channelartlist","\r\n        <li class=\"{dede:field.currentstyle/}\"> <a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a>\r\n          <div class=\"nav_dd dn\"> {dede:channel type='son' noself='yes'} <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> {/dede:channel} </div>\r\n        </li>\r\n        ",867,1298);
$z[2][4]['typeid']="top";
$z[2][4]['currentstyle']="on";

?>