<?php
$z[0]=Array("field","",301,320);
$z[0][4]['name']="title";
$z[1]=Array("global","",321,347);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1258,1297);
$z[2][4]['filename']="header_m.htm";
$z[3]=Array("field","",1527,1556);
$z[3][4]['name']="typename";
$z[4]=Array("global","",1899,1924);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("channel","\r\n        <li> <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\">&#xe60c;</span>\r\n          <dl>\r\n          </dl>\r\n        </li>\r\n        ",2335,2723);
$z[5][4]['type']="son";
$z[5][4]['row']="10";
$z[5][4]['typeid']="3";
$z[5][4]['currentstyle']="<li class='hover'><a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";
$z[6]=Array("field","",2826,2847);
$z[6][4]['name']="content";
$z[7]=Array("include","",2877,2916);
$z[7][4]['filename']="footer_m.htm";

?>