<?php
$z[0]=Array("global","",315,340);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("channel","\r\n          <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n          ",1737,1990);
$z[1][4]['type']="son";
$z[1][4]['typeid']="3";
$z[1][4]['currentstyle']="<li><a href='~typelink~' class='on'>~typename~</a></li>";
$z[2]=Array("arclist","\r\n        <li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a> </li>\r\n        ",2291,2469);
$z[2][4]['typeid']="2";
$z[2][4]['row']="5";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";

?>