<?php
$z[0]=Array("field","",111,130);
$z[0][4]['name']="title";
$z[1]=Array("global","",131,157);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",198,227);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",267,325);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",1028,1056);
$z[4][4]['name']="cfg_mobileurl";
$z[5]=Array("field","",1070,1086);
$z[5][4]['name']="id";
$z[6]=Array("global","",1555,1583);
$z[6][4]['name']="cfg_mobileurl";
$z[7]=Array("field","",1597,1613);
$z[7][4]['name']="id";
$z[8]=Array("include","",2719,2754);
$z[8][4]['filename']="head.htm";
$z[9]=Array("include","",2781,2816);
$z[9][4]['filename']="left.htm";
$z[10]=Array("field","",3189,3218);
$z[10][4]['name']="position";
$z[11]=Array("channel","\r\n          <li><a href='[field:typelink/]'>[field:typename/]</a> </li>\r\n          ",3250,3469);
$z[11][4]['type']="son";
$z[11][4]['typeid']="10";
$z[11][4]['row']="5";
$z[11][4]['currentstyle']="<li><a href='~typelink~' class='current'>~typename~</a></li>";
$z[12]=Array("list","\r\n          <li>\r\n            <div> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\"/></a>\r\n              <p class=\"prod-zoom\"></p>\r\n            </div>\r\n            <p><a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"pg-color\">[field:title/]</a></p>\r\n          </li>\r\n          ",3716,4087);
$z[12][4]['pagesize']="9";
$z[13]=Array("pagelist","",4133,4204);
$z[13][4]['listitem']="info,index,end,pre,next,pageno";
$z[13][4]['listsize']="5";
$z[14]=Array("include","",4303,4340);
$z[14][4]['filename']="footer.htm";

?>