<?php
$z[0]=Array("field","",301,320);
$z[0][4]['name']="title";
$z[1]=Array("global","",321,347);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1256,1295);
$z[2][4]['filename']="header_m.htm";
$z[3]=Array("field","",1525,1554);
$z[3][4]['name']="typename";
$z[4]=Array("global","",1897,1922);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("channel","\r\n        <li> <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\">&#xe60c;</span>\r\n          <dl>\r\n          </dl>\r\n        </li>\r\n        ",2333,2721);
$z[5][4]['type']="son";
$z[5][4]['row']="10";
$z[5][4]['typeid']="3";
$z[5][4]['currentstyle']="<li class='hover'><a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";
$z[6]=Array("list","\r\n      <li class=\"news1\" style=\"height: 107px;\"> <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"><span>[field:title/]</span><span>[field:pubdate function=\"MyDate('Y/m/d',@me)\"/]</span></a> </li>\r\n      ",2836,3086);
$z[6][4]['pagesize']="8";
$z[7]=Array("pagelist","",3139,3205);
$z[7][4]['listitem']="index,end,pre,next,pageno";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",3236,3275);
$z[8][4]['filename']="footer_m.htm";

?>