<?php
$z[0]=Array("field","",120,139);
$z[0][4]['name']="title";
$z[1]=Array("global","",140,166);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",210,239);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",282,340);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",1073,1101);
$z[4][4]['name']="cfg_mobileurl";
$z[5]=Array("field","",1115,1131);
$z[5][4]['name']="id";
$z[6]=Array("global","",1603,1631);
$z[6][4]['name']="cfg_mobileurl";
$z[7]=Array("field","",1645,1661);
$z[7][4]['name']="id";
$z[8]=Array("include","",3417,3452);
$z[8][4]['filename']="head.htm";
$z[9]=Array("include","",3484,3519);
$z[9][4]['filename']="left.htm";
$z[10]=Array("field","",3911,3940);
$z[10][4]['name']="position";
$z[11]=Array("channel","\r\n                            <li><a rel=\"[field:id/]\" href='[field:typelink/]'>[field:typename/]</a></li>\r\n                       ",3998,4188);
$z[11][4]['type']="son";
$z[11][4]['typeid']="2";
$z[11][4]['row']="5";
$z[12]=Array("list","\r\n         <li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"pg-color\">[field:title/]</a> <span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span> </li>\r\n         ",4481,4697);
$z[12][4]['pagesize']="20";
$z[13]=Array("pagelist","",4738,4809);
$z[13][4]['listitem']="info,index,end,pre,next,pageno";
$z[13][4]['listsize']="5";
$z[14]=Array("include","",4901,4938);
$z[14][4]['filename']="footer.htm";

?>