<?php
$z[0]=Array("field","",111,130);
$z[0][4]['name']="title";
$z[1]=Array("global","",131,157);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",198,227);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",267,325);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",1028,1056);
$z[4][4]['name']="cfg_mobileurl";
$z[5]=Array("field","",1070,1086);
$z[5][4]['name']="id";
$z[6]=Array("global","",1555,1583);
$z[6][4]['name']="cfg_mobileurl";
$z[7]=Array("field","",1597,1613);
$z[7][4]['name']="id";
$z[8]=Array("include","",3345,3380);
$z[8][4]['filename']="head.htm";
$z[9]=Array("include","",3407,3442);
$z[9][4]['filename']="left.htm";
$z[10]=Array("field","",3809,3838);
$z[10][4]['name']="position";
$z[11]=Array("channel","\r\n          <li><a href='[field:typelink/]'>[field:typename/]</a> </li>\r\n          ",3870,4088);
$z[11][4]['type']="son";
$z[11][4]['typeid']="3";
$z[11][4]['row']="5";
$z[11][4]['currentstyle']="<li><a href='~typelink~' class='current'>~typename~</a></li>";
$z[12]=Array("list","\r\n      <li>\r\n        <div> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\"/></a>\r\n          <p class=\"pg-border-color pro5-border1\"></p>\r\n          <p class=\"pg-border-color pro5-border2\"></p>\r\n          <p class=\"pg-border-color pro5-border3\"></p>\r\n          <p class=\"pg-border-color pro5-border4\"></p>\r\n        </div>\r\n        <p><a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"pg-color\">[field:title/]</a></p>\r\n      </li>\r\n      ",4301,4831);
$z[12][4]['pagesize']="9";
$z[13]=Array("pagelist","",4869,4940);
$z[13][4]['listitem']="info,index,end,pre,next,pageno";
$z[13][4]['listsize']="5";
$z[14]=Array("include","",5031,5068);
$z[14][4]['filename']="footer.htm";

?>